"""Add tasks and tasks statuses tables

Revision ID: 485c4f2872d4
Revises: 52efe109c313
Create Date: 2026-03-24 14:43:50.997046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "485c4f2872d4"
down_revision: Union[str, Sequence[str], None] = "52efe109c313"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_system_status_delete()
        RETURNS TRIGGER AS $$
        BEGIN
            IF OLD.id IN (
                '00000000-0000-0000-0000-000000000001',
                '00000000-0000-0000-0000-000000000002',
                '00000000-0000-0000-0000-000000000003',
                '00000000-0000-0000-0000-000000000004'
            ) THEN
                RAISE EXCEPTION 'Cannot delete system status: %', OLD.title;
            END IF;
            RETURN OLD;
        END;
        $$ LANGUAGE plpgsql;
    """
    )
    op.execute(
        """
        CREATE TRIGGER prevent_system_status_delete
        BEFORE DELETE ON task_statuses
        FOR EACH ROW
        EXECUTE FUNCTION prevent_system_status_delete();
    """
    )
    op.execute(
        """
        INSERT INTO task_statuses (id, title, color_hash, created_at, updated_at) VALUES
            ('00000000-0000-0000-0000-000000000001', 'To Do',       '#6b7280', now(), now()),
            ('00000000-0000-0000-0000-000000000002', 'In Progress', '#3b82f6', now(), now()),
            ('00000000-0000-0000-0000-000000000003', 'Review',      '#f59e0b', now(), now()),
            ('00000000-0000-0000-0000-000000000004', 'Done',        '#22c55e', now(), now())
        ON CONFLICT DO NOTHING;
    """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
