"""Add owner_id to team and ownership to user

Revision ID: 57740e498d10
Revises: c179aae4437b
Create Date: 2026-03-17 15:21:52.916423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57740e498d10'
down_revision: Union[str, Sequence[str], None] = 'c179aae4437b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'teams', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'owner_id')
    # ### end Alembic commands ###
