"""Modify User Entity

Revision ID: c179aae4437b
Revises: 3a7a8c1ab147
Create Date: 2026-03-14 19:19:33.976467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c179aae4437b'
down_revision: Union[str, Sequence[str], None] = '3a7a8c1ab147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###
